Pabii/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pabii.Models
{
    public class Category
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public CategoryEnum CategoryEnumeration { get; set; }
    }

    public enum CategoryEnum
    {
        [Display(Name = "Electronic Device")]
        ElectronicDevice,

        [Display(Name = "Electronic Accessories")]
        ElectronicAccessories,

        [Display(Name = "Appliances")]
        Appliances,

        [Display(Name = "Furniture")]
        Furniture,

        [Display(Name = "Men's Fashion")]
        MensFashion,

        [Display(Name = "Women's Fashion")]
        WomensFashion,
    }
}

Pabii/Models/ErrorViewModel.cs
using System;

namespace Pabii.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Pabii/Models/Products.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pabii.Models
{
    [Table("Products")]
    public class Products
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }

        [StringLength(50)]
        public string Name { get; set; }

        [StringLength(100)]
        public string Description { get; set; }

        [StringLength(50)]
        public string Image { get; set; }

        [DefaultValue(0)]
        public int Quantity { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Price { get; set; }

        [Required]
        public int Category { get; set; }

        [DefaultValue(0)]
        public int TotalRating { get; set; }

        [DefaultValue(0)]
        public int TotalRaters { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal? DiscountedPrice { get; set; }

        public int? DiscountPercent { get; set; }

        public DateTime? DiscountDateFrom { get; set; }

        public DateTime? DiscountDateTo { get; set; }
    }
}

Pabii/Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pabii.Models
{
    [Table("Users")]
    public class Users
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }

        public List<Products> Products { get; set; } = new List<Products>();
    }
}

Pabii/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Pabii.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class AccountController : Controller
    {
        private readonly Context context;

        [BindProperty]
        public LoginModel LoginModel { get; set; }

        public AccountController(Context _context)
        {
            context = _context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> SignIn()
        {
           
            return RedirectToAction("Login");
        }
    }

    public class LoginModel
    {
        [Required]
        [StringLength(15, MinimumLength = 7)]
        public string Username { get; set; }

        [Required]
        [StringLength(20, MinimumLength = 8)]
        public string Password { get; set; }
    }
}

Pabii/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Pabii.Models;

namespace Pabii.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pabii/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Pabii.Models;

namespace Pabii.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        private readonly Context _context;

        public HomeController(Context db)
        {
            _context = db;
        }

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetProducts(int? cat)
        {
            if (cat == null)
                return Json(new { data = await _context.Products.ToListAsync() });
            else
                return Json(new { data = await _context.Products.Where(x => x.Category == cat).ToListAsync() });
        }

        [HttpGet]
        [Route("api/[controller]/products")]
        public async Task<IActionResult> GetProducts()
        {
            return Json(new { data = await _context.Products.ToListAsync() });
        }

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

Pabii/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Pabii.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class MessageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pabii/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Pabii.Controllers
{
    [Authorize(AuthenticationSchemes = CookieAuthenticationDefaults.AuthenticationScheme)]
    public class ShopController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Pabii/Views/Cart/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Pabii/Views/Home/Index.cshtml
@model Category
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide min-width-300px" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Resources/Image/bb_0.jpg" alt="" style="width:100%;">
            </div>
            <div class="carousel-item">
                <img src="~/Resources/Image/bb_3.jpg" alt="" style="width:100%;">
            </div>
            <div class="carousel-item">
                <img src="~/Resources/Image/bb_2.jpg" alt="" style="width:100%;">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <br /><br />

    <div class="input-group m-auto min-width-300px width-75-percent">
        <input type="text" class="form-control" placeholder="What item are you looking for?" aria-label="Recipient's username" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="button">Search</button>
        </div>
    </div>

    <br />

    <div class="form-group m-auto min-width-300px width-75-percent">
        <select asp-for="CategoryEnumeration" class="form-control" asp-items="Html.GetEnumSelectList<CategoryEnum>()">
            <option selected="selected" value="">Select Category. . .</option>
        </select>
        <span asp-validation-for="CategoryEnumeration" class="text-danger"></span>
    </div>

    <br />

    <div id="div-row-contents" class="container m-auto min-width-300px">
    </div>

</div>

@section scripts{
    <script src="~/js/home.js" asp-append-version="true"></script>
}

Pabii/Views/Message/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

Pabii/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pabii</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" type="text/css" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 fixed-top" style="min-width:377px;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pabii</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav navbar-right">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">
                                Cart
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">
                                Shop
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Inbox" asp-action="Index">
                                Inbox
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Index">
                                Account
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Pabii - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- <style>
        .owe{
            background-color: pink;
        }
    </style> -->
    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Pabii/Views/Shop/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>